export const LOGIN_CONSTANTS = {
  EMAIL: "EMAIL",
  PASSWORD: "PASSWORD",
  EMAIL_ERROR: "EMAIL_ERROR",
  PASSWORD_ERROR: "PASSWORD_ERROR",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT:"LOGOUT"
};
